name: foodies_app
description: A Flutter application for food enthusiasts

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Existing dependencies
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geocoding: ^2.1.1
  http: ^1.1.0
  dio: ^5.3.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  url_launcher: ^6.2.1
  
  # NEW: Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env